[package]
name = "pru_gui"
version = "0.0.1"
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
eframe = { version = "0.27", default-features = true, features = ["glow"] }
pru_core = { path = "../pru_core" }
anyhow = { workspace = true }
